# Generated by Django 4.1.3 on 2023-05-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_movie_release_date_movie_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(default=1234),
        ),
    ]
